### ISSUE TITLE
org-mode does not highlight correctly

### ISSUE THREAD

**Issue by amirouche** [rails-to-cosmos/danneskjold-theme#2]
> `M-x version` 

25.2.2

> color-theme or emacs 24 theme

I don't know, I got the theme from melpa and I set it up with `M-x customize-theme`

The version reported by `M-x package-list-packages` is `20190130.1911`

> `M-: (face-at-point)`

`org-level-6` but it happens at other levels

> `M-x describe-face`

```
Face: org-level-6 (sample) (customize this face)

Documentation:
Face used for level 6 headlines.

Defined in ‘org-faces.el’.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: #FFFFFF
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified
```

> `M-: (display-color-cells)`

I cannot copy paste the output

> in gnome-terminal

org-mode is still not highlighted correctly

![danneskjold-theme-org-mode-bug](https://user-images.githubusercontent.com/7444897/52912916-64eaee00-32b8-11e9-809d-b194e188bb05.png)

Thanks for the awesome theme
